---
title: "R Notebook"
output: html_notebook

---
# 발달장애 유전자형 _"DDG2P_24_9_2019.with_pLI.txt"_


## pLI와 pRecs의 상관관계분석

```{r}
library(tidyverse)
library(readr)

e1 <- read_delim("DDG2P_24_9_2019.with_pLI.txt",delim='\t', col_names = T)
class(e1$pLI)
class(e1$pRec)
class(e1$pNull)

```

### pLI,pRec,pNull 추출
```{r}
e = subset(e1, select=c(pLI,pRec,pNull))
```

```{r}
cov(e) #공분산
cor(e, use = 'complete.obs',method = 'pearson')  #공분산을 표준화
```

## 상관계수의 검정
```{r}
cor.test(e$pLI,e$pRec)
```
  p-value < 2.2e-16  <- 귀무가설을 **기각 따라서 pLI와 pRecs 상관관계가 있다.**
  

## 시각화
```{r}
library(corrplot)
title <- "Correlation Coefficient"
ecor <- cor(e)
corrplot(ecor,title=title, method = 'shade', tl.col = 'black',addCoef.col="black", tl.srt = 10,order="FPC")

```

여기서

-1.0 <...< -0.7 사이이면, 강한 음적 선형관계,
-0.7 <...< -0.3 사이이면, 뚜렷한 음적 선형관계,
-0.3 <...<  -0.1 사이이면, 약한 음적 선형관계,
-0.1 <...< +0.1 사이이면, 거의 무시될 수 있는 선형관계,
+0.1 <...< +0.3 사이이면, 약한 양적 선형관계,
+0.3 <...< +0.7 사이이면, 뚜렷한 양적 선형관계,
+0.7 <...< +1.0 사이이면, 강한 양적 선형관계라고 할 수 있다.

#### **pLI와 pRec는 강한 음적 선형 관계이다.**

# tidyvers 이용한 코드
```{r}
plot_tfy <- read_delim("DDG2P_24_9_2019.with_pLI.txt",delim='\t', col_names = T) %>% subset( select=c(pLI,pRec,pNull)) %>% cor() %>% corrplot(title=title, method = 'shade', tl.col = 'black',addCoef.col="black", tl.srt = 10,order="FPC")
plot_tfy

```



