---
title: "R Notebook"
output: html_notebook
---
## 4.4 For-loops
The formula for the sum of the series  

 . What if we weren’t sure that was the right function? How could we check? Using what we learned about functions we can create one that computes the Sn
 
 _compute_s_n <- function(n){
  x <- 1:n
  sum(x)
}_

How can we compute S for various values of n Do we write 25 lines of code calling compute_s_n? No, that is what for-loops are for in programming. In this case, we are performing exactly the same task over and over, and the only thing that is changing is the value of n.

For-loops let us define the range that our variable takes  then change the value and evaluate expression as you loop.

Perhaps the simplest example of a for-loop is this useless piece of code:

_for(i in 1:5){
  print(i)
}
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
#> [1] 5_

Here is the for-loop we would write for our S example:

_m <- 25
s_n <- vector(length = m) # create an empty vector
for(n in 1:m){
  s_n[n] <- compute_s_n(n)
}_

In each iteration etc…, we compute S and store it in the th entry of s_n.

Now we can create a plot to search for a pattern:

_n <- 1:m
plot(n, s_n)_

If you noticed that it appears to be a quadratic, you are on the right track because the formula is  which we can confirm with a table:

_head(data.frame(s_n = s_n, formula = n*(n+1)/2))
#>   s_n formula
#> 1   1       1
#> 2   3       3
#> 3   6       6
#> 4  10      10
#> 5  15      15
#> 6  21      21_

We can also overlay the two results by using the function lines to draw a line over the previously plotted points:

_plot(n, s_n)
lines(n, n*(n+1)/2)_


## 4.5 Vectorization and functionals
Although for-loops are an important concept to understand, in R we rarely use them. As you learn more R, you will realize that vectorization is preferred over for-loops since it results in shorter and clearer code. We already saw examples in the Vector Arithmetic Section. A vectorized function is a function that will apply the same operation on each of the vectors.

_x <- 1:10
sqrt(x)
#>  [1] 1.00 1.41 1.73 2.00 2.24 2.45 2.65 2.83 3.00 3.16
y <- 1:10
x*y
#>  [1]   1   4   9  16  25  36  49  64  81 100_


To make this calculation, there is no need for for-loops. However, not all functions work this way. For instance, the function we just wrote, compute_s_n, does not work element-wise since it is expecting a scalar. This piece of code does not run the function on each entry of n:

_n <- 1:25
compute_s_n(n)_

Functionals are functions that help us apply the same function to each entry in a vector, matrix, data frame or list. Here we cover the functional that operates on numeric, logical and character vectors: sapply.

The function sapply permits us to perform element-wise operations on any function. Here is how it works:

_x <- 1:10
sapply(x, sqrt)
#>  [1] 1.00 1.41 1.73 2.00 2.24 2.45 2.65 2.83 3.00 3.16_

Each element of x is passed on to the function sqrt and the result is returned. These results are concatenated. In this case, the result is a vector of the same length as the original x. This implies that the for-loop above can be written as follows:

_n <- 1:25
s_n <- sapply(n, compute_s_n)
plot(n, s_n)_

Other functionals are apply, lapply, tapply, mapply, vapply, and replicate. We moslty use sapply, apply, and replicate in this book, but we recommend familiarizing yourselves with the others as they can be very useful.


## 4.6 Exercises
What will this conditional expression return?

x <- c(1,2,-3,4)

if(all(x>0)){
  print("All Postives")
} else{
  print("Not all positives")
}
Which of the following expressions is always FALSE when at least one entry of a logical vector x is TRUE?

A. all(x)

B. any(x)

C. any(!x)

D. all(!x)

The function nchar tells you how many characters long a character vector is.

Write a line of code that assigns to the object new_names the state abbreviation when the state name is longer than 8 characters.

Create a function sum_n that for any given value, say  
n
 , computes the sum of the integers from 1 to n (inclusive). Use the function to determine the sum of integers from 1 to 5,000.

Create a function altman_plot that takes two arguments, x and y, and plots the difference against the sum.

After running the code below, what is the value of x?

x <- 3
my_func <- function(y){
  x <- 5
  y+5
}
Write a function compute_s_n that for any given  
n
  computes the sum  
Report the value of the sum when  
Define an empty numerical vector s_n of size 25 using s_n <- vector("numeric", 25) and store in the results of using a for-loop.

Repeat exercise 8, but this time use sapply.

Repeat exercise 8, but this time use map_dbl.

Plot  
  versus  
 . Use points defined by  
Confirm that the formula for this sum is  
 .


```{r}
# 4.4
compute_s_n <- function(n){
  x <- 1:n
  sum(x)
}
for(i in 1:5){
  print(i)
}
m <- 25
s_n <- vector(length = m) # create an empty vector
for(n in 1:m){
  s_n[n] <- compute_s_n(n)
}
n <- 1:m
plot(n, s_n)
head(data.frame(s_n = s_n, formula = n*(n+1)/2))
plot(n, s_n)
lines(n, n*(n+1)/2)


# 4.5
x <- 1:10
sqrt(x)
y <- 1:10
x*y
n <- 1:25
compute_s_n(n)
x <- 1:10
sapply(x, sqrt)
n <- 1:25
s_n <- sapply(n, compute_s_n)
plot(n, s_n)


# 4.6
x <- c(1,2,-3,4)
if(all(x>0)){
  print("All Postives")
} else{
  print("Not all positives")
}
x <- 3
my_func <- function(y){
  x <- 5
  y+5
}


```

