---
title: "R Notebook"
output: html_notebook
---


```{r}
#1
B <- 10000
events <- replicate(B, sample(box,1))
#2
prop.table(events)
#3
set.seed(1106)
```
```{r}
#q1.
scores <- sample(0:100, 200, replace=TRUE)
mean(scores > 85)
m <- mean(scores)
s <- sd(scores)
mean(scores > 85)
#q2.
1-pnorm(85,m,s)
#q3.
pnorm(55,m,s) -pnorm(22,m,s)
```
```{r}
#q1.
n <- 2000
B <- 10000
Game <- function(n){
 X <- sample(c(2,-1), n, replace = TRUE, prob=c(335/1000,665/1000))
 sum(X)
}
S <- replicate(B, Game(n))
S
#q2
mean(S)
#q3
sd(S)
```
```{r}
#q1.
set.seed(1)
n <- 2000
B <- 10000
Game <- function(n){
X <- sample(c(1,-3), n, replace = TRUE, prob=c(6/10,4/10))
sum(X)
}
S <- replicate(B, Game(n))
S
#q2
sd(S)
#q3

pnorm(0, mean(S), sd(S))
```
```{r}
#1
p <- 0.4
N <- 2000
sqrt(p*(1-p))/sqrt(N)
#2
x_hat <- 0.48
se <- sqrt(x_hat*(1-x_hat)/30)
se
#3
pnorm(0.01/se) - pnorm(-0.01/se)

```
```{r}
#1
p <- 0.4
N <- 2000
x <- sample(c(0, 1), size = N, replace = TRUE, prob = c(1-p, p))
x_hat <- mean(x)
se_hat <- sqrt(x_hat * (1 - x_hat) / N)
c(x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
# 2
B <- 10000
inside <- replicate(B, {
  x <- sample(c(0,1), size = N, replace = TRUE, prob = c(1-p, p))
  x_hat <- mean(x)
  se_hat <- sqrt(x_hat * (1 - x_hat) / N)
  between(p, x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
})
mean(inside)
# 3
N <- 100
x_hat
t <-(2 * x_hat - 1) + c(-1.96, 1.96) * 2 * sqrt(x_hat * (1 - x_hat) / N)
plot(t)



```





