---
title: "R Notebook"
output: html_notebook
---




# 1
```{r}
library(dslabs)
data("heights")
heights %>% filter(sex=='Female') %>% ggplot(aes(height))+ggtitle('Female')+geom_density()
```
```{r}
heights %>% filter(sex=='Male') %>% ggplot(aes(height))+ggtitle('Male')+geom_density()
```
```{r}
females <- heights %>% filter(sex=='Female')
p_female <-length(which(females$height<=61))/length(females$height)
p_female

```

### 문제1

 랜덤으로 고른 여자의 키가 61인치보다 작을 확률은 약 12.1% 이다.
```{r}
# 2
set.seed(1)
B <- 1000
N <- 1000
red <- 19
blacks <- 16
greens <- 3
Game <- function(n){
 X <- sample(c(0,0,15), N, replace = TRUE, prob=c(19/38,16/38,3/38))
 sum(X)
}
set.seed(1)
S <- replicate(B, Game(n))

mean(S) # Expected Value
```
```{r}
sd(S) # stadard error

```
### 문제2

기대값은 1178.46 이 나오고 표준오차는 129.4374가 나온다.
즉 1000번 베팅을 하면 (1049.0226,1307.8974) 달러는 자연수이므로 1049~1307 달러를 얻을수 있다는 뜻이다.
```{r}
# 3
N <- 10
B <- 100
p <- 0.45
set.seed(1)
inside <- replicate(B, {
  x <- sample(c(0,1), size = N, replace = TRUE, prob = c(1-p, p))
  x_hat <- mean(x)
  se_hat <- sqrt(x_hat * (1 - x_hat) / N)
  between(p, x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
  return(c(x_hat,se_hat))
})
d <- t(inside)
mean(d)
sd(d)
```
```{r}
df <- as.data.frame(d) %>%
  rename(x_hat='V1',se_hat='V2') %>%
  mutate(Ci_low=x_hat - 1.96 * se_hat,
         Ci_high=x_hat + 1.96 * se_hat,
         p_inside=ifelse(Ci_low <= p & Ci_high >= p, 'Yes','No'))%>%
  mutate(n=seq(1,B))

g <- ggplot(df, aes(x_hat, n, colour=p_inside))
g + geom_point() +
  geom_errorbarh(aes(xmax= Ci_high, xmin= Ci_low))
```
### 문제3

N = 10, B = 100
[1] 0.2899518
 sd(d)
[1] 0.1811686


```{r}
N <- 1000
B <- 100
set.seed(1)
inside <- replicate(B, {
  x <- sample(c(0,1), size = N, replace = TRUE, prob = c(1-p, p))
  x_hat <- mean(x)
  se_hat <- sqrt(x_hat * (1 - x_hat) / N)
  between(p, x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
  return(c(x_hat,se_hat))
})
d <- t(inside)

mean(d)
sd(d)
```
```{r}
df <- as.data.frame(d) %>%
  rename(x_hat='V1',se_hat='V2') %>%
  mutate(Ci_low=x_hat - 1.96 * se_hat,
         Ci_high=x_hat + 1.96 * se_hat,
         p_inside=ifelse(Ci_low <= p & Ci_high >= p, 'Yes','No'))%>%
  mutate(n=seq(1,B))

g <- ggplot(df, aes(x_hat, n, colour=p_inside))
g + geom_point() +
  geom_errorbarh(aes(xmax= Ci_high, xmin= Ci_low))
```
N = 1000, B = 100
mean(d)
[1] 0.233203
sd(d)
[1] 0.2183184
```{r}
N <- 10
B <- 10000
set.seed(1)
inside <- replicate(B, {
  x <- sample(c(0,1), size = N, replace = TRUE, prob = c(1-p, p))
  x_hat <- mean(x)
  se_hat <- sqrt(x_hat * (1 - x_hat) / N)
  between(p, x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
  return(c(x_hat,se_hat))
})
d <- t(inside)
mean(d)
sd(d)
```
```{r}
df <- as.data.frame(d) %>%
  rename(x_hat='V1',se_hat='V2') %>%
  mutate(Ci_low=x_hat - 1.96 * se_hat,
         Ci_high=x_hat + 1.96 * se_hat,
         p_inside=ifelse(Ci_low <= p & Ci_high >= p, 'Yes','No'))%>%
  mutate(n=seq(1,B))

g <- ggplot(df, aes(x_hat, n, colour=p_inside))
g + geom_point() +
  geom_errorbarh(aes(xmax= Ci_high, xmin= Ci_low))
```
N = 10, B = 10000
 mean(d)
[1] 0.2995999
 sd(d)
[1] 0.1879142
```{r}
N <- 1000
B <- 10000
set.seed(1)
inside <- replicate(B, {
  x <- sample(c(0,1), size = N, replace = TRUE, prob = c(1-p, p))
  x_hat <- mean(x)
  se_hat <- sqrt(x_hat * (1 - x_hat) / N)
  between(p, x_hat - 1.96 * se_hat, x_hat + 1.96 * se_hat)
  return(c(x_hat,se_hat))
})
d <- t(inside)
mean(d)
sd(d)
```
```{r}
df <- as.data.frame(d) %>%
  rename(x_hat='V1',se_hat='V2') %>%
  mutate(Ci_low=x_hat - 1.96 * se_hat,
         Ci_high=x_hat + 1.96 * se_hat,
         p_inside=ifelse(Ci_low <= p & Ci_high >= p, 'Yes','No'))%>%
  mutate(n=seq(1,B))

g <- ggplot(df, aes(x_hat, n, colour=p_inside))
g + geom_point() +
  geom_errorbarh(aes(xmax= Ci_high, xmin= Ci_low))
```

N = 10, B = 100
[1] 0.2899518
 sd(d)
[1] 0.1811686

N = 1000, B = 100
mean(d)
[1] 0.233203
sd(d)
[1] 0.2183184

N = 10, B = 10000
 mean(d)
[1] 0.2995999
 sd(d)
[1] 0.1879142

N = 1000, B = 10000
 mean(d)
[1] 0.2328974
 sd(d)
[1] 0.2174646

N이 클수록 기대값이 작아지고 편차가 커진다





